export const FETCH_THIRDPARTYAPI_REQUEST = "FETCH_THIRDPARTYAPI_REQUEST";
export const FETCH_THIRDPARTYAPI_SUCCESS = "FETCH_THIRDPARTYAPI_SUCCESS";
export const FETCH_THIRDPARTYAPI_FAILURE = "FETCH_THIRDPARTYAPI_FAILURE";
